server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

mock:
  ifood:
    semente: 42
    caos:
      enabled: true
      delay-ms-min: 200
      delay-ms-max: 2000
      error-rate: 0.08
      timeout-rate: 0.03
      timeout-ms: 12000
